# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.box_check_update = false
  config.vm.synced_folder "shared/", "/vagrant"

  config.vm.define "mb" do |mb|
    mb.vm.network "forwarded_port", guest: 5000, host: 5001
    mb.vm.hostname = "mb"
    mb.vm.provision :shell, :path => "mosaicbin.sh"
  end

end
